name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choisir l'environnement"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Déployer
        run: echo "Déploiement vers ${{ inputs.environment }}"